#!/usr/bin/env python3
"""
Generate sitemap.xml for bennettvet.com from the current site state.
Run before every deploy. The deploy.ps1 wrapper does this automatically.

Behavior:
- Auto-discovers all .html files in the project
- Skips noindex pages (privacy, accessibility, etc.) per Google's guidance:
  noindex pages should not appear in sitemaps
- Skips 404.html (HTTP error page, not crawlable content)
- Skips thank-you/ (form-success redirect target, no value to crawler)
- Skips local-only helper docs (deploy-netlify-steps, setup-github-steps —
  also gitignored, but excluded here too as a safety net)
- Auto-extracts lastmod from each file's mtime (strongest sitemap signal
  Google uses; changefreq and priority are mostly ignored per Google's own
  documentation — we include priority anyway as a hint for crawl-prioritization)
- Auto-extracts image:image entries from each page's schema.org ImageObject
  JSON-LD so image sitemap entries stay in sync with the actual page content
"""

import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://bennettvet.com"

EXCLUDE_FILES = {"404.html", "deploy-netlify-steps.html", "setup-github-steps.html"}
EXCLUDE_DIRS = {"thank-you", "node_modules", "dist", ".cache", ".netlify"}


def priority_for(url_path):
    """Hint to crawlers about relative importance within the site."""
    if url_path == "/":
        return "1.0"
    if url_path == "/in-home-pet-euthanasia/":
        return "0.9"
    if url_path in ("/services/", "/contact/"):
        return "0.7"
    if url_path == "/about/":
        return "0.6"
    if url_path.count("/") == 2:
        return "0.7"
    return "0.5"


def file_to_url_path(html_file):
    rel = html_file.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel


def is_noindex(html_content):
    return bool(re.search(
        r'<meta\s+name="robots"\s+content="[^"]*noindex',
        html_content, re.IGNORECASE))


def extract_image_object(html_content):
    """Find first JSON-LD ImageObject. Returns (url, caption) or None."""
    m = re.search(
        r'"image"\s*:\s*\{[^}]*?"url"\s*:\s*"([^"]+)"'
        r'[^}]*?"caption"\s*:\s*"([^"]+)"',
        html_content, re.DOTALL)
    if m:
        return (m.group(1), m.group(2))
    m = re.search(
        r'"image"\s*:\s*"([^"]+)"', html_content)
    if m:
        return (m.group(1), None)
    return None


def file_mtime_iso(p):
    return datetime.fromtimestamp(
        p.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%d")


def collect_urls():
    urls = []
    for html_file in sorted(ROOT.rglob("*.html")):
        rel_parts = html_file.relative_to(ROOT).parts
        if html_file.name in EXCLUDE_FILES:
            continue
        if any(part in EXCLUDE_DIRS for part in rel_parts):
            continue
        if any(part.startswith(".") for part in rel_parts):
            continue
        try:
            content = html_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if is_noindex(content):
            continue
        url_path = file_to_url_path(html_file)
        urls.append({
            "url": BASE_URL + url_path,
            "path": url_path,
            "lastmod": file_mtime_iso(html_file),
            "priority": priority_for(url_path),
            "image": extract_image_object(content),
        })
    return urls


def xml_escape(s):
    return (s.replace("&", "&amp;")
              .replace("<", "&lt;")
              .replace(">", "&gt;")
              .replace('"', "&quot;")
              .replace("'", "&apos;"))


def build_sitemap(urls):
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
           '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
           '  <!-- Auto-generated by scripts/build-sitemap.py. Do not edit by hand. -->',
           '']
    for u in urls:
        out.append('  <url>')
        out.append(f'    <loc>{xml_escape(u["url"])}</loc>')
        out.append(f'    <lastmod>{u["lastmod"]}</lastmod>')
        out.append(f'    <priority>{u["priority"]}</priority>')
        if u["image"]:
            img_url, img_caption = u["image"]
            out.append('    <image:image>')
            out.append(f'      <image:loc>{xml_escape(img_url)}</image:loc>')
            if img_caption:
                out.append(f'      <image:caption>{xml_escape(img_caption)}</image:caption>')
            out.append('    </image:image>')
        out.append('  </url>')
    out.append('</urlset>')
    return "\n".join(out) + "\n"


def main():
    urls = collect_urls()
    sitemap = build_sitemap(urls)
    out_path = ROOT / "sitemap.xml"
    out_path.write_text(sitemap, encoding="utf-8", newline="\n")
    image_count = sum(1 for u in urls if u["image"])
    print(f"Wrote {out_path}")
    print(f"  {len(urls)} URLs ({image_count} with image entries)")
    print(f"  Excluded: noindex pages, 404, thank-you, helper docs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
